export const ADD_TECNICO_REQUESTED = "tecnico@ADD_TECNICO_REQUESTED"
export const ADD_TECNICO_SUCCESS =   "tecnico@ADD_TECNICO_SUCCESS"
export const ADD_TECNICO_FAILED  =   "tecnico@ADD_TECNICO_FAILED"

export const LIST_TECNICO_REQUESTED = "tecnico@LIST_TECNICO_REQUESTED"
export const LIST_TECNICO_SUCCESS =   "tecnico@LIST_TECNICO_SUCCESS"
export const LIST_TECNICO_FAILED  =   "tecnico@LIST_TECNICO_FAILED"


export const DELETE_TECNICO_REQUESTED = "tecnico@DELETE_TECNICO_REQUESTED"
export const DELETE_TECNICO_SUCCESS =   "tecnico@DELETE_TECNICO_SUCCESS"
export const DELETE_TECNICO_FAILED  =   "tecnico@DELETE_TECNICO_FAILED"


export const UPDATE_TECNICO_REQUESTED = "tecnico@UPDATE_TECNICO_REQUESTED"
export const UPDATE_TECNICO_SUCCESS =   "tecnico@UPDATE_TECNICO_SUCCESS"
export const UPDATE_TECNICO_FAILED  =   "tecnico@UPDATE_TECNICO_FAILED"


export const CLEAR_TECNICO_FIELDS  =   "tecnico@CLEAR_TECNICO_FIELDS"


