export const CREATE_PRODUCT_REQUESTED = "produtc@CREATE_PRODUCT_REQUESTED"
export const CREATE_PRODUCT_SUCCESS =   "produtc@CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILED  =   "produtc@CREATE_PRODUCT_FAILED"


export const DELETE_PRODUCT_REQUESTED = "produtc@DELETE_PRODUCT_REQUESTED"
export const DELETE_PRODUCT_SUCCESS =   "produtc@DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILED  =   "produtc@DELETE_PRODUCT_FAILED"


export const UPDATE_PRODUCT_REQUESTED = "produtc@UPDATE_PRODUCT_REQUESTED"
export const UPDATE_PRODUCT_SUCCESS =   "produtc@UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAILED  =   "produtc@UPDATE_PRODUCT_FAILED"

